pipeline:
  git:
    image: plugins/git
    tags: true
  docker-build-publish:
    image: plugins/docker
    repo: foo/bar
    secrets: [ docker_username, docker_password ]
    dry_run: true
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: dist/*
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
    when:
      event: tag
