pipeline:
  docker-build-publish:
    image: plugins/docker
    repo: foo/bar
    secrets: [ docker_username, docker_password ]
    dry_run: true
pipeline:
  github_release:
    image: plugins/github-release
    api_key: ${API_SECRET}
    files: dist/*
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
